//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
<<<<<<< HEAD
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobtrack {
    
    
    public partial class _Default {
        
        /// <summary>
        /// imgLogo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image imgLogo;
=======
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobtrack
{


    public partial class _Default
    {
>>>>>>> 2220a9e743f0919fba1b548c90491d82c5d4cf6f
    }
}
